name: Build for Mac OS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Backlooper version'
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install
        run: python -m pip install "backlooper==$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Install development requirements
        run: python -m pip install -r dev-requirements.txt
      - name: Build
        run: python -m PyInstaller src\backlooper\__main__.py --add-data "src/backlooper/samples:backlooper/samples" --onefile --name "backlooper-$VERSION" --icon pyinstaller/icon.png
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist/
